from __future__ import annotations

import re
from pathlib import Path


# nf-validation 1.x set these as *params*; nf-schema 2.x replaced them with options in the
# `validation` config scope. The mapping is the official migration guide's, verbatim:
# https://nextflow-io.github.io/nf-schema/latest/migration_guide/
_REMOVED_PARAMS = {
    "validationSchemaIgnoreParams": "validation.defaultIgnoreParams",
    "validationIgnoreParams": "validation.ignoreParams",
    "validationMonochromeLogs": "validation.monochromeLogs",
    "validationLenientMode": "validation.lenientMode",
    "validationFailUnrecognisedParams": "validation.failUnrecognisedParams",
    "validationShowHiddenParams": "validation.showHiddenParams",
}
_ASSIGNMENT = re.compile(
    r"^\s*(" + "|".join(_REMOVED_PARAMS) + r")\s*=", re.MULTILINE)
# `plugins { id 'nf-schema@2.5.1' }` — the plugin (and major version) the release actually declares.
_PLUGIN = re.compile(r"id\s+['\"]nf-(schema|validation)@(\d+)")

# Pinned plugin releases with a known, inert bug that a run reproduces faithfully — nf-claw wraps
# releases unmodified, so the bug ships as-is. Keyed on the exact `id@version` the release declares,
# so the advisory clears itself the moment the pin moves to a fixed version. Value: what the run will
# show and why, written to be read on its own.
_KNOWN_PLUGIN_BUGS = {
    "nf-core-utils@0.4.0":
        "logs `WARN ... nf-core pipelines do not accept positional arguments. The positional "
        "argument `nextflow` has been detected.` to .nextflow.log on every run. Its "
        "pipeline observer hands the whole command line — which always begins with the launcher word "
        "`nextflow` — to a positional-argument check that expects the (normally empty) positional "
        "argument list, so `nextflow` is mis-flagged as a positional argument. It is inert: a "
        "`log.warn`, the run completes, and it is not produced by nf-claw. An upstream nf-core-utils "
        "bug; see docs/known-issues.md.",
}
# `id 'nf-core-utils@0.4.0'` → the exact plugin id and full version a release declares.
_PLUGIN_ID = re.compile(r"id\s+['\"]([A-Za-z0-9_-]+@[0-9]+\.[0-9]+\.[0-9]+)['\"]")


def _declares_nf_schema_v2(config: Path) -> bool:
    """True when the release declares nf-schema 2.x (where the 1.x params below no longer exist)."""
    try:
        text = config.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    m = _PLUGIN.search(text)
    return bool(m) and m.group(1) == "schema" and int(m.group(2)) >= 2


def _detect(upstream: Path) -> dict[str, list[str]]:
    """{removed-param name: the config files that set it}, for a pinned nf-schema-2.x release.

    Empty unless the release declares nf-schema 2.x *and* still sets one of the nf-validation 1.x
    params it removed. Deterministic and narrow by construction: a release that declares
    nf-validation 1.x is using these params *correctly* and is never matched.
    """
    main_config = upstream / "nextflow.config"
    if not _declares_nf_schema_v2(main_config):
        return {}
    configs = [main_config] + sorted((upstream / "conf").glob("*.config"))
    where: dict[str, list[str]] = {}
    for config in configs:
        try:
            text = config.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for name in dict.fromkeys(_ASSIGNMENT.findall(text)):
            where.setdefault(name, []).append(config.relative_to(upstream).as_posix())
    return where


def removed_params_in_use(upstream: Path) -> list[str]:
    """The nf-validation 1.x parameter names a pinned nf-schema-2.x release still sets, sorted.

    Empty unless the defect `check()` describes is present. `nfclaw run` feeds these to
    `write_ignore_params_config` so nf-schema stops reporting them as invalid — without editing the
    pinned tree.
    """
    return sorted(_detect(upstream))


def write_ignore_params_config(names: list[str], path: Path) -> Path:
    """Generate a Nextflow config that adds `names` to nf-schema's `validation.ignoreParams`.

    This is the officially documented lever for "parameters validation should not flag":
    https://nextflow-io.github.io/nf-schema/latest/configuration/ . Listing the obsolete param names
    there makes nf-schema skip them, so its inert "not a valid parameter" warning does not appear —
    while the pinned release tree stays byte-identical (drift-check green) and results are unaffected
    (`ignoreParams` changes only what validation *warns about*). `ignoreParams` is the user-facing
    list, separate from the pipeline's own `validation.defaultIgnoreParams`, so it adds to that list
    rather than replacing it.
    """
    listed = ", ".join(f"'{n}'" for n in names)
    path.write_text(
        "// Generated by nfclaw. The pinned release still sets nf-validation 1.x parameter(s) that\n"
        "// nf-schema 2.x removed; adding their names to validation.ignoreParams suppresses the inert\n"
        "// 'not a valid parameter' warning without modifying the release. See docs/known-issues.md.\n"
        f"validation {{ ignoreParams = [{listed}] }}\n",
        encoding="utf-8")
    return path


def check(upstream: Path) -> list[str]:
    """Advisory: a pinned release that declares nf-schema 2.x but still sets an nf-validation 1.x param.

    nf-schema 2.x does not know these params, and the pipeline's own schema does not declare them
    either, so Nextflow would report the parameter as invalid — a warning the run would otherwise
    carry for no reason anyone reading the log can see. It is inert: the option does nothing and
    results are unaffected. nf-claw wraps each release **unmodified**, so the release itself is not
    edited; instead `nfclaw run` neutralises the warning at the config layer (see
    `write_ignore_params_config`) and this advisory records that it did, so the behaviour is not
    mistaken for nf-claw hiding a real fault.

    Deterministic, and narrow by construction: a release that declares nf-validation 1.x is using
    these params *correctly* and is never flagged. Only the nf-schema-2.x-plus-1.x-param combination
    — the actual defect — is reported.
    """
    # One advisory per offending parameter, naming every config that sets it — the same release
    # typically repeats the option across its test profiles, and repeating the whole explanation
    # once per file would bury the run's own output.
    return [
        f"the pinned release sets `{name}` in {', '.join(files)}: an nf-validation 1.x parameter "
        f"removed in nf-schema 2.x, which this release declares (the replacement is the "
        f"`{_REMOVED_PARAMS[name]}` config option). It is inert and does not affect results; nf-claw "
        f"neutralises the warning by adding `{name}` to nf-schema's `validation.ignoreParams` via a "
        f"generated `-c` config, leaving the pinned release untouched. See docs/known-issues.md."
        for name, files in _detect(upstream).items()
    ]


def known_plugin_warnings(upstream: Path) -> list[str]:
    """Advisory: the pinned release declares a plugin version with a known, inert bug.

    Unlike the nf-schema param above, these warnings cannot be neutralised from nf-claw — they are
    emitted by the plugin's own observer, with no config lever — so the honest fix is to surface them
    up front, explained, rather than let the run print an alarming message with no visible cause.
    Deterministic and self-clearing: keyed on the exact `id@version` the release declares (see
    `_KNOWN_PLUGIN_BUGS`), so a pin bump to a fixed version silences the advisory automatically.
    """
    try:
        text = (upstream / "nextflow.config").read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    return [f"the pinned release declares `{pid}`, which {_KNOWN_PLUGIN_BUGS[pid]}"
            for pid in dict.fromkeys(_PLUGIN_ID.findall(text)) if pid in _KNOWN_PLUGIN_BUGS]
